import type { CallFact, Finding } from '../types.js';

const EXCLUDED_CALLEES = new Set([
  'Date',
  'Map',
  'Set',
  'WeakMap',
  'WeakSet',
  'Array',
  'Error',
  'RegExp',
  'Promise',
  'URL',
  'URLSearchParams',
  'Buffer',
  'Headers',
  'Request',
  'Response',
  'FormData',
  'Blob',
  'File',
  'ArrayBuffer',
  'Uint8Array',
  'Int32Array',
  'Float32Array',
  'AbortController',
  // NestJS exceptions & utilities
  'HttpException',
  'BadRequestException',
  'UnauthorizedException',
  'NotFoundException',
  'ForbiddenException',
  'NotAcceptableException',
  'RequestTimeoutException',
  'ConflictException',
  'GoneException',
  'PayloadTooLargeException',
  'UnsupportedMediaTypeException',
  'UnprocessableEntityException',
  'InternalServerErrorException',
  'NotImplementedException',
  'HttpVersionNotSupportedException',
  'BadGatewayException',
  'ServiceUnavailableException',
  'GatewayTimeoutException',
  'ImATeapotException',
  'MethodNotAllowedException',
  'Logger',
  // Angular & RxJS primitives / forms / HTTP
  'EventEmitter',
  'BehaviorSubject',
  'Subject',
  'ReplaySubject',
  'AsyncSubject',
  'Observable',
  'Subscription',
  'FormGroup',
  'FormControl',
  'FormArray',
  'FormBuilder',
  'Validators',
  'HttpHeaders',
  'HttpParams',
  'ElementRef',
  'TemplateRef',
  'ViewContainerRef',
]);

export function dipDirectInstantiation(facts: CallFact[]): Finding[] {
  return facts
    .filter((fact) => fact.isNewExpression && !EXCLUDED_CALLEES.has(fact.calleeExpression))
    .map((fact) => ({
      ruleId: 'dip/direct-instantiation',
      principle: 'SOLID',
      severity: 'info',
      confidence: 'medium',
      message: `Direct instantiation of '${fact.calleeExpression}' inside a class method bypasses dependency injection`,
      location: fact.location,
    }));
}
